export interface BroadTopic {
  id: number;
  title: string;
  specificTopics: string[];
}

export const broadTopics: BroadTopic[] = [
  {
    id: 1,
    title: "Evolutionary Change",
    specificTopics: [
      "Evolutionary Genetics",
      "Thermal Tolerance",
      "Ecosystem Ecology",
    ],
  },
  {
    id: 2,
    title: "Systems Biology",
    specificTopics: [
      "Cellular Networks",
      "Statistical Modeling",
      "Epidemiology",
      "Data Clustering",
      "Metabolic Pathways",
      "Academic Research",
    ],
  },
  {
    id: 3,
    title: "Animal Behavior",
    specificTopics: [
      "Evolutionary Biology",
      "Butterfly Colors",
      "Social Networks",
      "Optimal Foraging",
      "Ecological Niche",
      "Behavioral Tracking",
      "Bird Migration",
      "Animal Communication",
      "Animal Behaviour",
      "Primates",
    ],
  },
  {
    id: 4,
    title: "Zoonotic Diseases",
    specificTopics: ["Avian Influenza", "Livestock Disease", "Bats and Rabies"],
  },
  {
    id: 5,
    title: "Evolutionary Dynamics",
    specificTopics: [
      "Genetic Mutations",
      "Bacterial Growth",
      "Evolutionary Biology",
      "Aging",
      "Ecosystem Dynamics",
      "Disease Transmission",
      "Microbial Communities",
    ],
  },
  {
    id: 6,
    title: "Genetic Engineering",
    specificTopics: [
      "Genetic Evolution",
      "Biological Circuits",
      "Biotech",
      "Bacterial Genetics",
      "Transposons",
      "Antibiotic Resistance",
      "Microbial Evolution",
      "Bacteriophage Therapy",
      "Bacterial Defense",
    ],
  },
  {
    id: 7,
    title: "Genetics",
    specificTopics: [
      "Sex Determination",
      "Human Genetics",
      "Genetic Diversity",
      "Anatomy",
      "Genetics",
      "Soybean Genetics",
      "Genetic Recombination",
      "Plant Genomes",
      "Evolutionary Biology",
      "Genomics",
      "Plant Biology",
      "Species Identification",
      "Animal Health",
    ],
  },
  {
    id: 8,
    title: "Neural Networks",
    specificTopics: [
      "Neural Plasticity",
      "Brain Connectivity",
      "Brain Networks",
      "Artificial Intelligence",
      "Brain Waves",
      "Brain Computer",
      "Neural Dynamics",
      "Neuroscience",
    ],
  },
  {
    id: 9,
    title: "Genetic Traits",
    specificTopics: [
      "Genetic Regulation",
      "Genetic Traits",
      "Genetic Analysis",
      "Heart Health",
    ],
  },
  {
    id: 10,
    title: "Genetic Evolution",
    specificTopics: [
      "Genetics",
      "Genetic Selection",
      "Population Genetics",
      "Evolutionary Biology",
      "Crop Genetics",
    ],
  },
  {
    id: 11,
    title: "Noncoding RNAs",
    specificTopics: ["MicroRNAs", "Noncoding RNAs", "RNA Biology"],
  },
  {
    id: 12,
    title: "Ecosystem Management",
    specificTopics: [
      "Ecological Diversity",
      "Biodiversity Conservation",
      "Forestry",
      "Botany",
      "Statistical Modelling",
      "Wildlife Tracking",
      "Wildfire Ecology",
    ],
  },
  {
    id: 13,
    title: "Genomics",
    specificTopics: [
      "Gene Expression",
      "Bioinformatics",
      "DNA Origami",
      "Genetic Variation",
      "Genomics",
      "Genome Assembly",
      "Genomic Visualization",
      "Cancer Detection",
      "Antibiotic Resistance",
      "Microbial Genomics",
    ],
  },
  {
    id: 14,
    title: "Protein Networks",
    specificTopics: [
      "Systems Biology",
      "Protein Modeling",
      "Scientific Software",
      "Genomics",
      "Bioinformatics",
      "Protein Interactions",
    ],
  },
  {
    id: 15,
    title: "Glioblastoma",
    specificTopics: [
      "Evolutionary Biology",
      "Cancer Microenvironment",
      "Cancer Biomarkers",
      "Genetic Mutations",
      "Cancer Genomics",
      "Pharmacology",
      "Brain Cancer",
    ],
  },
  {
    id: 16,
    title: "Liver Inflammation",
    specificTopics: [
      "Inflammation Response",
      "Viral Infection",
      "Immune Response",
      "Immune Cells",
      "Autoimmune Disease",
      "Liver Disease",
    ],
  },
  {
    id: 17,
    title: "HIV Research",
    specificTopics: ["HIV Cure", "Viral Disease", "Viral Assembly"],
  },
  {
    id: 18,
    title: "Plant Stress",
    specificTopics: [
      "Plant Development",
      "Immune Response",
      "Photosynthesis",
      "RNA Regulation",
      "Cell Signaling",
      "Wheat Genetics",
      "Metabolic Pathway",
      "Plant Stress",
    ],
  },
  {
    id: 19,
    title: "Pharmaceuticals",
    specificTopics: [
      "Plant Extracts",
      "Enzyme Inhibitors",
      "Machine Learning",
      "Toxicology",
      "Cell Signaling",
      "Peptide Sequences",
    ],
  },
  {
    id: 20,
    title: "Nematode Biology",
    specificTopics: [
      "Neural Behavior",
      "Cell Biology",
      "Genetic Variation",
      "Genome Defense",
      "Aging",
    ],
  },
  {
    id: 21,
    title: "Protein Structure",
    specificTopics: [
      "Biological Assemblies",
      "Molecular Dynamics",
      "Protein Binding",
      "Genetic Evolution",
      "Biochemistry",
      "Protein Structure",
      "Protein Disorder",
      "Biomolecular Condensation",
    ],
  },
  {
    id: 22,
    title: "Aging",
    specificTopics: [
      "Telomere Maintenance",
      "Cell Differentiation",
      "Cell Signaling",
      "Genomic Regulation",
      "Transcription Factors",
      "Cell Death",
      "Aging",
      "Hypoxia Response",
    ],
  },
  {
    id: 23,
    title: "Soil Microbiology",
    specificTopics: [
      "Plant Disease",
      "Fungi Ecology",
      "Soil Science",
      "Plant Microbiome",
    ],
  },
  {
    id: 24,
    title: "Alzheimer's Disease",
    specificTopics: [
      "Alzheimer's Disease",
      "Alzheimer's Diagnosis",
      "Genetic Risk",
      "Tauopathies",
    ],
  },
  {
    id: 25,
    title: "Parkinsons Disease",
    specificTopics: [
      "Genetic Disorders",
      "Parkinsons Disease",
      "Eye Disease",
      "Spinal Cord Injury",
      "Neurodevelopment",
      "Neurodegenerative",
      "Epilepsy Genetics",
      "Nutrition",
      "Neuroprotective Agents",
      "Multiple Sclerosis",
      "Genetic Disease",
      "Huntington's Disease",
      "Immune Response",
    ],
  },
  {
    id: 26,
    title: "Psychological Disorders",
    specificTopics: [
      "Cannabis",
      "Reproductive Hormones",
      "Schizophrenia Genetics",
      "Food Preferences",
      "Autism Disorder",
      "Social Behavior",
      "Psychedelic Drugs",
      "Pregnancy and Birth",
      "Stress Disorders",
      "Substance Abuse",
      "Neural Plasticity",
      "Mental Health Disorder",
      "Brain Injury",
      "Alcohol Abuse",
      "Fetal Alcohol",
    ],
  },
  {
    id: 27,
    title: "Embryonic Development",
    specificTopics: [
      "Stem Cell Biology",
      "Stem Cell",
      "Gene Regulation",
      "Pregnancy",
      "Cell Morphology",
      "Blood Cells",
      "Ovarian Development",
      "Neuroscience",
      "Women's Health",
    ],
  },
  {
    id: 28,
    title: "Mitochondria",
    specificTopics: [
      "Mitochondria",
      "Genetic Evolution",
      "Oxidative Stress",
      "Parkinsons Disease",
    ],
  },
  {
    id: 29,
    title: "Microbial Pathogens",
    specificTopics: [
      "Fungal Genetics",
      "Parasite Biology",
      "Infection Response",
      "Clostridium difficile",
      "Infections",
      "Bacterial Infections",
      "Insect Toxins",
      "Disease Outbreak",
      "Fungal Infections",
      "Toxoplasmosis",
    ],
  },
  {
    id: 30,
    title: "Neuroscience",
    specificTopics: [
      "Neuroscience",
      "Neurotransmitter System",
      "Epilepsy",
      "Parkinsons Disease",
      "Neurology",
      "Sensory Perception",
      "Neuroanatomy",
      "Motor Control",
      "Neurotransmission",
    ],
  },
  {
    id: 31,
    title: "Muscle Kinematics",
    specificTopics: ["Exercise Physiology", "Motor Control"],
  },
  {
    id: 32,
    title: "Biomedical Imaging",
    specificTopics: ["Neuro Imaging", "Neurostimulation"],
  },
  {
    id: 33,
    title: "Learning Theory",
    specificTopics: [
      "Brain Function",
      "Learning Theory",
      "Motor Learning",
      "Cognitive Control",
      "Brain Chemistry",
      "Social Brain",
    ],
  },
  {
    id: 34,
    title: "Memory and Fear",
    specificTopics: [
      "Brain Navigation",
      "Neuroscience",
      "Memory Processes",
      "PTSD Response",
    ],
  },
  {
    id: 35,
    title: "Virology",
    specificTopics: [
      "Genetic Evolution",
      "Viral Structure",
      "Microbial Diversity",
      "Herpesvirus",
      "Zika Virus",
      "Gene Therapy",
      "Viral Infections",
      "Immune Response",
    ],
  },
  {
    id: 36,
    title: "Single Cell",
    specificTopics: [
      "Neuroscience",
      "Single Cell Omics",
      "Genomic Regulation",
      "Developmental Dynamics",
      "Single Cell Analysis",
      "Biology",
    ],
  },
  {
    id: 37,
    title: "Malaria",
    specificTopics: [
      "Plant Extracts",
      "Parasite Biology",
      "Malaria Control",
      "Antimalarial Treatment",
      "Malaria Immunity",
    ],
  },
  {
    id: 38,
    title: "Influenza Virus",
    specificTopics: ["Vaccine Science", "Viral Replication"],
  },
  {
    id: 39,
    title: "Gene Expression",
    specificTopics: [
      "Genetics",
      "RNA Structure",
      "Protein Synthesis",
      "Biological Noise",
      "Gene Expression",
      "Neuronal Plasticity",
      "mRNA degradation",
      "RNA Binding",
      "Protein Translation",
    ],
  },
  {
    id: 40,
    title: "Microscopy",
    specificTopics: [
      "Fluorescence Microscopy",
      "Biosensor Technology",
      "CryoEM Structures",
      "Microscopy",
      "Software Tools",
    ],
  },
  {
    id: 41,
    title: "Microbial Ecology",
    specificTopics: [
      "Brewing",
      "Environmental Science",
      "Biochemical Engineering",
      "Symbiotic Relationships",
      "Ocean Ecosystems",
      "Microbiology",
      "Water Treatment",
      "Antibiotic Resistance",
    ],
  },
  {
    id: 42,
    title: "Immune Response",
    specificTopics: [
      "Immune Repertoire",
      "HIV Vaccine",
      "Antibody Therapeutics",
      "Cancer Immunology",
    ],
  },
  {
    id: 43,
    title: "Cell Division",
    specificTopics: [
      "Cell Growth",
      "Cell Motility",
      "Cell Division",
      "Meiotic Process",
      "Mitotic Spindle",
      "Cell Signaling",
    ],
  },
  {
    id: 44,
    title: "Honeybees",
    specificTopics: [
      "Kinematics",
      "Ant Colonies",
      "Honeybee Behavior",
      "Bee Health",
    ],
  },
  {
    id: 45,
    title: "Genome Regulation",
    specificTopics: [
      "Epigenetics",
      "Chromosome Organization",
      "Cell Division",
      "Chromatin Dynamics",
      "DNA Repair",
      "DNA Replication",
      "RNA Modification",
    ],
  },
  {
    id: 46,
    title: "Neural Development",
    specificTopics: [
      "Evolutionary Biology",
      "Neuroscience",
      "Zebrafish Genetics",
      "Developmental Biology",
      "Bone Health",
      "Fibrosis",
    ],
  },
  {
    id: 47,
    title: "Bacterial Biofilm",
    specificTopics: [
      "Glycosylation",
      "Bacterial Regulation",
      "Cell Wall",
      "Iron Metabolism",
      "Biochemical Pathway",
      "Bacterial Division",
      "Bacterial Motility",
      "Protein Degradation",
      "Bacterial Secretion",
      "Biofilm Formation",
    ],
  },
  {
    id: 48,
    title: "Marine Biology",
    specificTopics: [
      "Environmental DNA",
      "Salmon Genetics",
      "Climate Change",
      "Marine Mammals",
      "Water Quality",
      "Marine Fisheries",
      "Coral Reef",
      "Evolutionary Biology",
      "Aquatic Toxicity",
    ],
  },
  {
    id: 49,
    title: "Cell Mechanics",
    specificTopics: [
      "Cell Transport",
      "Cellular Mechanics",
      "Cell Migration",
      "Cell Adhesion",
      "Musculoskeletal",
      "Mechanosensitive channels",
    ],
  },
  {
    id: 50,
    title: "Epigenetic Aging",
    specificTopics: [
      "Genetic Risk",
      "Genome Methylation",
      "Epigenetics",
      "Plant Evolution",
      "Aging",
    ],
  },
  {
    id: 51,
    title: "Cell Biology",
    specificTopics: [
      "Calcium Signaling",
      "Cell Biology",
      "Cell Signaling",
      "Immune Signaling",
      "Lipid Metabolism",
      "Cell Membranes",
      "Protein Modification",
      "Neuroscience",
      "Cell Trafficking",
      "Neurotransmission",
      "Protein Enzyme",
      "Protein Structure",
      "Stress Response",
      "Alzheimer's Disease",
      "Cellular Degradation",
      "Cilia Structure",
      "Cell Junctions",
    ],
  },
  {
    id: 52,
    title: "Brain Processing",
    specificTopics: [
      "Brain Function",
      "Computer Vision",
      "Neural Responses",
      "Brain Mapping",
      "Perceptual Timing",
      "Spatial Navigation",
      "Language Processing",
      "Emotion Regulation",
    ],
  },
  {
    id: 53,
    title: "Hearing",
    specificTopics: [
      "Smell System",
      "Auditory Processing",
      "Music Theory",
      "Speech Processing",
      "Hearing Loss",
    ],
  },
  {
    id: 54,
    title: "Drosophila Biology",
    specificTopics: [
      "Developmental Biology",
      "Neural Circuits",
      "Genetic Regulation",
      "Reproductive Biology",
      "Nutrition",
    ],
  },
  {
    id: 55,
    title: "Disease Control",
    specificTopics: [
      "Developmental Biology",
      "Parasite Genomics",
      "Bacterial Symbionts",
      "Sensory Chemistry",
      "Mosquito Control",
      "Herbivore Pests",
      "Disease Surveillance",
    ],
  },
  {
    id: 56,
    title: "Brain Development",
    specificTopics: [
      "Psychiatric Disorders",
      "Aging",
      "Neurological Disease",
      "Cognitive Decline",
      "Neonatal Development",
    ],
  },
  {
    id: 57,
    title: "Protein Analysis",
    specificTopics: ["Metabolic Flux", "Protein Analysis", "Mass Spectrometry"],
  },
  {
    id: 58,
    title: "Pulmonary Disease",
    specificTopics: [
      "Pulmonary Fibrosis",
      "Respiratory Health",
      "Cystic Fibrosis",
    ],
  },
  {
    id: 59,
    title: "Agriculture",
    specificTopics: [
      "Agriculture",
      "Microbial Resistance",
      "Microplastic Pollution",
      "Fruit Development",
      "Plant Phenotyping",
    ],
  },
  {
    id: 60,
    title: "Decision Making",
    specificTopics: ["Metacognition", "Neural Decision"],
  },
  {
    id: 61,
    title: "Diabetes Management",
    specificTopics: [
      "Pancreatic Cells",
      "Obesity Research",
      "Diabetes",
      "Adipose Tissue",
    ],
  },
  {
    id: 62,
    title: "Gene Editing",
    specificTopics: [
      "CRISPR Screening",
      "Genetic Engineering",
      "RNA Editing",
      "Immune Defense",
    ],
  },
  {
    id: 63,
    title: "Neuroimaging",
    specificTopics: ["Medical Simulation"],
  },
  {
    id: 64,
    title: "Thermoregulation",
    specificTopics: ["Biology", "Hibernation Physiology"],
  },
  {
    id: 65,
    title: "Cancer Treatment",
    specificTopics: [
      "Blood Cancer",
      "Cancer",
      "Cancer Signaling",
      "Metabolic Pathways",
      "Cancer Metastasis",
      "Breast Cancer",
      "Cancer Genes",
      "Pancreatic Cancer",
      "Cancer Treatment",
      "Lung Cancer",
    ],
  },
  {
    id: 66,
    title: "Ion Channels",
    specificTopics: ["Ion Channel", "Cell Transport", "Pain Receptors"],
  },
  {
    id: 67,
    title: "Inflammatory Bowel",
    specificTopics: ["Intestinal Cells", "Inflammatory Bowel"],
  },
  {
    id: 68,
    title: "Cell Imaging",
    specificTopics: ["Medical Imaging", "Immune Cell"],
  },
  {
    id: 69,
    title: "TB Disease",
    specificTopics: ["Antibiotic Resistance", "Bovine TB", "Tuberculosis"],
  },
  {
    id: 70,
    title: "Zebrafish Biology",
    specificTopics: ["Genomic Evolution", "Animal Behavior"],
  },
  {
    id: 71,
    title: "Medical Imaging",
    specificTopics: [
      "Brain Mapping",
      "Neuroimaging Analysis",
      "Neuroimaging",
      "Magnetic Resonance",
      "Medical Imaging",
    ],
  },
  {
    id: 72,
    title: "Cancer Immunotherapy",
    specificTopics: [
      "Immune System",
      "Immune Cells",
      "Cancer Therapy",
      "Cancer Treatment",
    ],
  },
  {
    id: 73,
    title: "Cardiovascular",
    specificTopics: [
      "Atherosclerosis",
      "Vascular System",
      "Medical Imaging",
      "Cardiac Physiology",
      "Cardiac Disease",
      "Neurological Disorders",
      "Vascular Biology",
      "Kidney Disease",
      "Pulmonary Hypertension",
    ],
  },
  {
    id: 74,
    title: "Microbial Health",
    specificTopics: [
      "Genomics Analysis",
      "Oral Health",
      "Evolutionary Biology",
      "Metabolic Changes",
      "Vaginal Health",
    ],
  },
  {
    id: 75,
    title: "Health Education",
    specificTopics: [
      "Academic Careers",
      "Childhood Obesity",
      "Healthcare",
      "Global Health",
      "Addiction Genetics",
    ],
  },
  {
    id: 76,
    title: "Muscle Disease",
    specificTopics: ["Muscle Regeneration", "Muscular Dystrophy"],
  },
  {
    id: 77,
    title: "Sleep Rhythms",
    specificTopics: [
      "Brain Activity",
      "Sleep Health",
      "Circadian Rhythms",
      "Memory Consolidation",
    ],
  },
  {
    id: 78,
    title: "Pain Management",
    specificTopics: ["Neurological Pain", "Pain Perception", "Substance Abuse"],
  },
  {
    id: 79,
    title: "Tissue Engineering",
    specificTopics: [
      "Microfluidics",
      "Nanoparticle Delivery",
      "Tissue Regeneration",
      "Bioprinting Materials",
      "Organoid Models",
    ],
  },
  {
    id: 80,
    title: "Eye Vision",
    specificTopics: ["Attention", "Vision", "Eye Cells", "Eye Movement"],
  },
  {
    id: 81,
    title: "Photosynthesis",
    specificTopics: [
      "Ocean Microbiology",
      "Biological Optics",
      "Photosynthesis",
      "Cyanobacteria",
    ],
  },
  {
    id: 82,
    title: "Brain Stimulation",
    specificTopics: ["Brain Stimulation", "Anesthesia"],
  },
  {
    id: 83,
    title: "Antiviral Drugs",
    specificTopics: ["Dengue Fever", "Viral Diseases", "COVID-19"],
  },
  {
    id: 84,
    title: "Exosome Biology",
    specificTopics: ["Stem Cell Biology", "Biomarker Analysis"],
  },
  {
    id: 85,
    title: "COVID Vaccine",
    specificTopics: [
      "Vaccine Development",
      "Immune Response",
      "Molecular Testing",
      "COVID-19",
      "Nanoparticle Delivery",
    ],
  },
  {
    id: 86,
    title: "Staphylococcal Infections",
    specificTopics: ["Medical"],
  },
  {
    id: 87,
    title: "COVID-19",
    specificTopics: [
      "Genomics",
      "Viral Replication",
      "Viral Entry",
      "COVID Disease",
      "Antibody Response",
      "Virus Variants",
      "COVID Vaccine",
    ],
  },
  {
    id: 88,
    title: "Research Paper",
    specificTopics: ["Research Paper"],
  },
];

export const specificTopics = [
  "Evolutionary Genetics",
  "Thermal Tolerance",
  "Ecosystem Ecology",
  "Cellular Networks",
  "Statistical Modeling",
  "Epidemiology",
  "Data Clustering",
  "Metabolic Pathways",
  "Academic Research",
  "Evolutionary Biology",
  "Butterfly Colors",
  "Social Networks",
  "Optimal Foraging",
  "Ecological Niche",
  "Behavioral Tracking",
  "Bird Migration",
  "Animal Communication",
  "Animal Behaviour",
  "Primates",
  "Avian Influenza",
  "Livestock Disease",
  "Bats and Rabies",
  "Genetic Mutations",
  "Bacterial Growth",
  "Evolutionary Biology",
  "Aging",
  "Ecosystem Dynamics",
  "Disease Transmission",
  "Microbial Communities",
  "Genetic Evolution",
  "Biological Circuits",
  "Biotech",
  "Bacterial Genetics",
  "Transposons",
  "Antibiotic Resistance",
  "Microbial Evolution",
  "Bacteriophage Therapy",
  "Bacterial Defense",
  "Sex Determination",
  "Human Genetics",
  "Genetic Diversity",
  "Anatomy",
  "Genetics",
  "Soybean Genetics",
  "Genetic Recombination",
  "Plant Genomes",
  "Evolutionary Biology",
  "Genomics",
  "Plant Biology",
  "Species Identification",
  "Animal Health",
  "Neural Plasticity",
  "Brain Connectivity",
  "Brain Networks",
  "Artificial Intelligence",
  "Brain Waves",
  "Brain Computer",
  "Neural Dynamics",
  "Neuroscience",
  "Genetic Regulation",
  "Genetic Traits",
  "Genetic Analysis",
  "Heart Health",
  "Genetics",
  "Genetic Selection",
  "Population Genetics",
  "Evolutionary Biology",
  "Crop Genetics",
  "MicroRNAs",
  "Noncoding RNAs",
  "RNA Biology",
  "Ecological Diversity",
  "Biodiversity Conservation",
  "Forestry",
  "Botany",
  "Statistical Modelling",
  "Wildlife Tracking",
  "Wildfire Ecology",
  "Gene Expression",
  "Bioinformatics",
  "DNA Origami",
  "Genetic Variation",
  "Genomics",
  "Genome Assembly",
  "Genomic Visualization",
  "Cancer Detection",
  "Antibiotic Resistance",
  "Microbial Genomics",
  "Systems Biology",
  "Protein Modeling",
  "Scientific Software",
  "Genomics",
  "Bioinformatics",
  "Protein Interactions",
  "Evolutionary Biology",
  "Cancer Microenvironment",
  "Cancer Biomarkers",
  "Genetic Mutations",
  "Cancer Genomics",
  "Pharmacology",
  "Brain Cancer",
  "Inflammation Response",
  "Viral Infection",
  "Immune Response",
  "Immune Cells",
  "Autoimmune Disease",
  "Liver Disease",
  "HIV Cure",
  "Viral Disease",
  "Viral Assembly",
  "Plant Development",
  "Immune Response",
  "Photosynthesis",
  "RNA Regulation",
  "Cell Signaling",
  "Wheat Genetics",
  "Metabolic Pathway",
  "Plant Stress",
  "Plant Extracts",
  "Enzyme Inhibitors",
  "Machine Learning",
  "Toxicology",
  "Cell Signaling",
  "Peptide Sequences",
  "Neural Behavior",
  "Cell Biology",
  "Genetic Variation",
  "Genome Defense",
  "Aging",
  "Biological Assemblies",
  "Molecular Dynamics",
  "Protein Binding",
  "Genetic Evolution",
  "Biochemistry",
  "Protein Structure",
  "Protein Disorder",
  "Biomolecular Condensation",
  "Telomere Maintenance",
  "Cell Differentiation",
  "Cell Signaling",
  "Genomic Regulation",
  "Transcription Factors",
  "Cell Death",
  "Aging",
  "Hypoxia Response",
  "Plant Disease",
  "Fungi Ecology",
  "Soil Science",
  "Plant Microbiome",
  "Alzheimer's Disease",
  "Alzheimer's Diagnosis",
  "Genetic Risk",
  "Tauopathies",
  "Genetic Disorders",
  "Parkinsons Disease",
  "Eye Disease",
  "Spinal Cord Injury",
  "Neurodevelopment",
  "Neurodegenerative",
  "Epilepsy Genetics",
  "Nutrition",
  "Neuroprotective Agents",
  "Multiple Sclerosis",
  "Genetic Disease",
  "Huntington's Disease",
  "Immune Response",
  "Cannabis",
  "Reproductive Hormones",
  "Schizophrenia Genetics",
  "Food Preferences",
  "Autism Disorder",
  "Social Behavior",
  "Psychedelic Drugs",
  "Pregnancy and Birth",
  "Stress Disorders",
  "Substance Abuse",
  "Neural Plasticity",
  "Mental Health Disorder",
  "Brain Injury",
  "Alcohol Abuse",
  "Fetal Alcohol",
  "Stem Cell Biology",
  "Stem Cell",
  "Gene Regulation",
  "Pregnancy",
  "Cell Morphology",
  "Blood Cells",
  "Ovarian Development",
  "Neuroscience",
  "Women's Health",
  "Mitochondria",
  "Genetic Evolution",
  "Oxidative Stress",
  "Parkinsons Disease",
  "Fungal Genetics",
  "Parasite Biology",
  "Infection Response",
  "Clostridium difficile",
  "Infections",
  "Bacterial Infections",
  "Insect Toxins",
  "Disease Outbreak",
  "Fungal Infections",
  "Toxoplasmosis",
  "Neuroscience",
  "Neurotransmitter System",
  "Epilepsy",
  "Parkinsons Disease",
  "Neurology",
  "Sensory Perception",
  "Neuroanatomy",
  "Motor Control",
  "Neurotransmission",
  "Exercise Physiology",
  "Motor Control",
  "Neuro Imaging",
  "Neurostimulation",
  "Brain Function",
  "Learning Theory",
  "Motor Learning",
  "Cognitive Control",
  "Brain Chemistry",
  "Social Brain",
  "Brain Navigation",
  "Neuroscience",
  "Memory Processes",
  "PTSD Response",
  "Genetic Evolution",
  "Viral Structure",
  "Microbial Diversity",
  "Herpesvirus",
  "Zika Virus",
  "Gene Therapy",
  "Viral Infections",
  "Immune Response",
  "Neuroscience",
  "Single Cell Omics",
  "Genomic Regulation",
  "Developmental Dynamics",
  "Single Cell Analysis",
  "Biology",
  "Plant Extracts",
  "Parasite Biology",
  "Malaria Control",
  "Antimalarial Treatment",
  "Malaria Immunity",
  "Vaccine Science",
  "Viral Replication",
  "Genetics",
  "RNA Structure",
  "Protein Synthesis",
  "Biological Noise",
  "Gene Expression",
  "Neuronal Plasticity",
  "mRNA degradation",
  "RNA Binding",
  "Protein Translation",
  "Fluorescence Microscopy",
  "Biosensor Technology",
  "CryoEM Structures",
  "Microscopy",
  "Software Tools",
  "Brewing",
  "Environmental Science",
  "Biochemical Engineering",
  "Symbiotic Relationships",
  "Ocean Ecosystems",
  "Microbiology",
  "Water Treatment",
  "Antibiotic Resistance",
  "Immune Repertoire",
  "HIV Vaccine",
  "Antibody Therapeutics",
  "Cancer Immunology",
  "Cell Growth",
  "Cell Motility",
  "Cell Division",
  "Meiotic Process",
  "Mitotic Spindle",
  "Cell Signaling",
  "Kinematics",
  "Ant Colonies",
  "Honeybee Behavior",
  "Bee Health",
  "Epigenetics",
  "Chromosome Organization",
  "Cell Division",
  "Chromatin Dynamics",
  "DNA Repair",
  "DNA Replication",
  "RNA Modification",
  "Evolutionary Biology",
  "Neuroscience",
  "Zebrafish Genetics",
  "Developmental Biology",
  "Bone Health",
  "Fibrosis",
  "Glycosylation",
  "Bacterial Regulation",
  "Cell Wall",
  "Iron Metabolism",
  "Biochemical Pathway",
  "Bacterial Division",
  "Bacterial Motility",
  "Protein Degradation",
  "Bacterial Secretion",
  "Biofilm Formation",
  "Environmental DNA",
  "Salmon Genetics",
  "Climate Change",
  "Marine Mammals",
  "Water Quality",
  "Marine Fisheries",
  "Coral Reef",
  "Evolutionary Biology",
  "Aquatic Toxicity",
  "Cell Transport",
  "Cellular Mechanics",
  "Cell Migration",
  "Cell Adhesion",
  "Musculoskeletal",
  "Mechanosensitive channels",
  "Genetic Risk",
  "Genome Methylation",
  "Epigenetics",
  "Plant Evolution",
  "Aging",
  "Calcium Signaling",
  "Cell Biology",
  "Cell Signaling",
  "Immune Signaling",
  "Lipid Metabolism",
  "Cell Membranes",
  "Protein Modification",
  "Neuroscience",
  "Cell Trafficking",
  "Neurotransmission",
  "Protein Enzyme",
  "Protein Structure",
  "Stress Response",
  "Alzheimer's Disease",
  "Cellular Degradation",
  "Cilia Structure",
  "Cell Junctions",
  "Brain Function",
  "Computer Vision",
  "Neural Responses",
  "Brain Mapping",
  "Perceptual Timing",
  "Spatial Navigation",
  "Language Processing",
  "Emotion Regulation",
  "Smell System",
  "Auditory Processing",
  "Music Theory",
  "Speech Processing",
  "Hearing Loss",
  "Developmental Biology",
  "Neural Circuits",
  "Genetic Regulation",
  "Reproductive Biology",
  "Nutrition",
  "Developmental Biology",
  "Parasite Genomics",
  "Bacterial Symbionts",
  "Sensory Chemistry",
  "Mosquito Control",
  "Herbivore Pests",
  "Disease Surveillance",
  "Psychiatric Disorders",
  "Aging",
  "Neurological Disease",
  "Cognitive Decline",
  "Neonatal Development",
  "Metabolic Flux",
  "Protein Analysis",
  "Mass Spectrometry",
  "Pulmonary Fibrosis",
  "Respiratory Health",
  "Cystic Fibrosis",
  "Agriculture",
  "Microbial Resistance",
  "Microplastic Pollution",
  "Fruit Development",
  "Plant Phenotyping",
  "Metacognition",
  "Neural Decision",
  "Pancreatic Cells",
  "Obesity Research",
  "Diabetes",
  "Adipose Tissue",
  "CRISPR Screening",
  "Genetic Engineering",
  "RNA Editing",
  "Immune Defense",
  "Medical Simulation",
  "Biology",
  "Hibernation Physiology",
  "Blood Cancer",
  "Cancer",
  "Cancer Signaling",
  "Metabolic Pathways",
  "Cancer Metastasis",
  "Breast Cancer",
  "Cancer Genes",
  "Pancreatic Cancer",
  "Cancer Treatment",
  "Lung Cancer",
  "Ion Channel",
  "Cell Transport",
  "Pain Receptors",
  "Intestinal Cells",
  "Inflammatory Bowel",
  "Medical Imaging",
  "Immune Cell",
  "Antibiotic Resistance",
  "Bovine TB",
  "Tuberculosis",
  "Genomic Evolution",
  "Animal Behavior",
  "Brain Mapping",
  "Neuroimaging Analysis",
  "Neuroimaging",
  "Magnetic Resonance",
  "Medical Imaging",
  "Immune System",
  "Immune Cells",
  "Cancer Therapy",
  "Cancer Treatment",
  "Atherosclerosis",
  "Vascular System",
  "Medical Imaging",
  "Cardiac Physiology",
  "Cardiac Disease",
  "Neurological Disorders",
  "Vascular Biology",
  "Kidney Disease",
  "Pulmonary Hypertension",
  "Genomics Analysis",
  "Oral Health",
  "Evolutionary Biology",
  "Metabolic Changes",
  "Vaginal Health",
  "Academic Careers",
  "Childhood Obesity",
  "Healthcare",
  "Global Health",
  "Addiction Genetics",
  "Muscle Regeneration",
  "Muscular Dystrophy",
  "Brain Activity",
  "Sleep Health",
  "Circadian Rhythms",
  "Memory Consolidation",
  "Neurological Pain",
  "Pain Perception",
  "Substance Abuse",
  "Microfluidics",
  "Nanoparticle Delivery",
  "Tissue Regeneration",
  "Bioprinting Materials",
  "Organoid Models",
  "Attention",
  "Vision",
  "Eye Cells",
  "Eye Movement",
  "Ocean Microbiology",
  "Biological Optics",
  "Photosynthesis",
  "Cyanobacteria",
  "Brain Stimulation",
  "Anesthesia",
  "Dengue Fever",
  "Viral Diseases",
  "COVID-19",
  "Stem Cell Biology",
  "Biomarker Analysis",
  "Vaccine Development",
  "Immune Response",
  "Molecular Testing",
  "COVID-19",
  "Nanoparticle Delivery",
  "Medical",
  "Genomics",
  "Viral Replication",
  "Viral Entry",
  "COVID Disease",
  "Antibody Response",
  "Virus Variants",
  "COVID Vaccine",
  "Research Paper",
];
