export interface BroadTopic {
  id: number;
  title: string;
  specificTopics: string[];
}

export const broadTopics: BroadTopic[] = [
  {
    id: 1,
    title: "Aging",
    specificTopics: [
      "Telomere Maintenance",
      "Cell Differentiation",
      "Cell Signaling",
      "Genomic Regulation",
      "Transcription Factors",
      "Cell Death",
      "Aging",
      "Hypoxia Response",
    ],
  },
  {
    id: 2,
    title: "Agriculture",
    specificTopics: [
      "Agriculture",
      "Microbial Resistance",
      "Microplastic Pollution",
      "Fruit Development",
      "Plant Phenotyping",
    ],
  },
  {
    id: 3,
    title: "Alzheimer's Disease",
    specificTopics: [
      "Alzheimer's Disease",
      "Alzheimer's Diagnosis",
      "Genetic Risk",
      "Tauopathies",
    ],
  },
  {
    id: 4,
    title: "Animal Behavior",
    specificTopics: [
      "Evolutionary Biology",
      "Color Phenotypes",
      "Social Networks",
      "Population-Level Dynamics",
      "Ecological Niche",
      "Behavioral Tracking",
      "Bird Migration",
      "Animal Communication",
      "Animal Behavior",
      "Primates",
    ],
  },
  {
    id: 5,
    title: "Antiviral Drugs",
    specificTopics: ["Dengue Fever", "Viral Diseases", "COVID-19"],
  },
  {
    id: 6,
    title: "Bacterial Biofilm",
    specificTopics: [
      "Glycosylation",
      "Bacterial Regulation",
      "Cell Wall",
      "Iron Metabolism",
      "Biochemical Pathway",
      "Bacterial Division",
      "Bacterial Motility",
      "Protein Degradation",
      "Bacterial Secretion",
      "Biofilm Formation",
    ],
  },
  {
    id: 7,
    title: "Biomedical Imaging",
    specificTopics: ["Neuroimaging", "Neurostimulation"],
  },
  {
    id: 8,
    title: "Brain Development",
    specificTopics: [
      "Psychiatric Disorders",
      "Aging",
      "Neurological Disease",
      "Cognitive Decline",
      "Neonatal Development",
    ],
  },
  {
    id: 9,
    title: "Brain Stimulation",
    specificTopics: ["Brain Stimulation", "Anesthesia"],
  },
  {
    id: 10,
    title: "COVID Vaccine",
    specificTopics: [
      "Vaccine Development",
      "Immune Response",
      "Molecular Testing",
      "COVID-19",
      "Nanoparticle Delivery",
    ],
  },
  {
    id: 11,
    title: "COVID-19",
    specificTopics: [
      "Genomics",
      "Viral Replication",
      "Viral Entry",
      "COVID-19",
      "Antibody Response",
      "Virus Variants",
      "COVID Vaccine",
    ],
  },
  {
    id: 12,
    title: "Cancer Immunotherapy",
    specificTopics: ["Immune System", "Immune Cells", "Cancer Therapy"],
  },
  {
    id: 13,
    title: "Cancer Treatment",
    specificTopics: [
      "Blood Cancer",
      "Cancer",
      "Cancer Signaling",
      "Metabolic Pathway",
      "Cancer Metastasis",
      "Breast Cancer",
      "Cancer Genes",
      "Pancreatic Cancer",
      "Cancer Therapy",
      "Lung Cancer",
    ],
  },
  {
    id: 14,
    title: "Cardiovascular Biology",
    specificTopics: [
      "Atherosclerosis",
      "Vascular System",
      "Medical Imaging",
      "Cardiac Physiology",
      "Cardiac Disease",
      "Neurological Disease",
      "Vascular Biology",
      "Kidney Disease",
      "Pulmonary Hypertension",
    ],
  },
  {
    id: 15,
    title: "Cell Biology",
    specificTopics: [
      "Calcium Signaling",
      "Cell Biology",
      "Cell Signaling",
      "Immune Signaling",
      "Lipid Metabolism",
      "Cell Membranes",
      "Protein Modification",
      "Neuroscience",
      "Cell Trafficking",
      "Neurotransmission",
      "Enzymology",
      "Protein Structure",
      "Stress Response",
      "Alzheimer's Disease",
      "Cellular Degradation",
      "Cilia Structure",
      "Cell Junctions",
    ],
  },
  {
    id: 16,
    title: "Cell Division",
    specificTopics: [
      "Cell Growth",
      "Cell Motility",
      "Cell Division",
      "Meiotic Process",
      "Mitotic Spindle",
      "Cell Signaling",
    ],
  },
  {
    id: 17,
    title: "Cell Imaging",
    specificTopics: ["Medical Imaging", "Immune Cells"],
  },
  {
    id: 18,
    title: "Cell Mechanics",
    specificTopics: [
      "Cell Transport",
      "Cellular Mechanics",
      "Cell Migration",
      "Cell Adhesion",
      "Musculoskeletal",
      "Mechanosensitive channels",
    ],
  },
  {
    id: 19,
    title: "Cortical Systems and Sensory Processing",
    specificTopics: [
      "Brain Function",
      "Computer Vision",
      "Neural Responses",
      "Brain Mapping",
      "Perceptual Timing",
      "Spatial Navigation",
      "Language Processing",
      "Emotion Regulation",
    ],
  },
  {
    id: 20,
    title: "Decision Making",
    specificTopics: ["Metacognition", "Neural Decision"],
  },
  {
    id: 21,
    title: "Diabetes Management",
    specificTopics: [
      "Pancreatic Cells",
      "Obesity Research",
      "Diabetes",
      "Adipose Tissue",
    ],
  },
  {
    id: 22,
    title: "Disease Control",
    specificTopics: [
      "Developmental Biology",
      "Parasite Genomics",
      "Bacterial Symbionts",
      "Sensory Chemistry",
      "Mosquito Control",
      "Herbivore Pests",
      "Disease Surveillance",
    ],
  },
  {
    id: 23,
    title: "Drosophila Biology",
    specificTopics: [
      "Developmental Biology",
      "Neural Circuits",
      "Gene Regulation",
      "Reproductive Biology",
      "Nutrition",
    ],
  },
  {
    id: 24,
    title: "Ecosystem Management",
    specificTopics: [
      "Ecological Diversity",
      "Biodiversity Conservation",
      "Forestry",
      "Botany",
      "Statistical Modelling",
      "Wildlife Tracking",
      "Wildfire Ecology",
    ],
  },
  {
    id: 25,
    title: "Embryonic Development",
    specificTopics: [
      "Stem Cell Biology",
      "Stem Cell",
      "Gene Regulation",
      "Pregnancy",
      "Cell Morphology",
      "Blood Cells",
      "Ovarian Development",
      "Neuroscience",
      "Women's Health",
    ],
  },
  {
    id: 26,
    title: "Epigenetic Aging",
    specificTopics: [
      "Genetic Risk",
      "Genome Methylation",
      "Epigenetics",
      "Plant Evolution",
      "Aging",
    ],
  },
  {
    id: 27,
    title: "Evolutionary Change",
    specificTopics: [
      "Evolutionary Genetics",
      "Thermal Tolerance",
      "Ecosystem Ecology",
    ],
  },
  {
    id: 28,
    title: "Evolutionary Dynamics",
    specificTopics: [
      "Genetic Mutations",
      "Bacterial Growth",
      "Evolutionary Biology",
      "Aging",
      "Ecosystem Dynamics",
      "Disease Transmission",
      "Microbial Communities",
    ],
  },
  {
    id: 29,
    title: "Exosome Biology",
    specificTopics: ["Stem Cell Biology", "Biomarker Analysis"],
  },
  {
    id: 30,
    title: "Eye and Vision Biology",
    specificTopics: ["Attention", "Vision", "Eye Cells", "Eye Movement"],
  },
  {
    id: 31,
    title: "Gene Editing",
    specificTopics: [
      "CRISPR Screening",
      "Genetic Engineering",
      "RNA Editing",
      "Immune Defense",
    ],
  },
  {
    id: 32,
    title: "Gene Expression",
    specificTopics: [
      "Genetics",
      "RNA Structure",
      "Protein Synthesis",
      "Biological Noise",
      "Gene Expression",
      "Neural Plasticity",
      "mRNA degradation",
      "RNA Binding",
      "Protein Translation",
    ],
  },
  {
    id: 33,
    title: "Genetic Engineering",
    specificTopics: [
      "Evolutionary Genetics",
      "Biological Circuits",
      "Technology Development",
      "Bacterial Genetics",
      "Transposons",
      "Antibiotic Resistance",
      "Microbial Evolution",
      "Bacteriophage Therapy",
      "Bacterial Defense",
    ],
  },
  {
    id: 34,
    title: "Genetic Evolution",
    specificTopics: [
      "Genetics",
      "Genetic Selection",
      "Population Genetics",
      "Evolutionary Biology",
      "Crop Genetics",
    ],
  },
  {
    id: 35,
    title: "Genetic Traits",
    specificTopics: [
      "Gene Regulation",
      "Genetic Traits",
      "Genetic Analysis",
      "Heart Health",
    ],
  },
  {
    id: 36,
    title: "Genetics",
    specificTopics: [
      "Sex Determination",
      "Human Genetics",
      "Genetic Diversity",
      "Anatomy",
      "Genetics",
      "Soybean Genetics",
      "Genetic Recombination",
      "Plant Genomes",
      "Evolutionary Biology",
      "Genomics",
      "Plant Biology",
      "Species Identification",
      "Animal Health",
    ],
  },
  {
    id: 37,
    title: "Genome Regulation",
    specificTopics: [
      "Epigenetics",
      "Chromosome Organization",
      "Cell Division",
      "Chromatin Dynamics",
      "DNA Repair",
      "DNA Replication",
      "RNA Modification",
    ],
  },
  {
    id: 38,
    title: "Genomics",
    specificTopics: [
      "Gene Expression",
      "Bioinformatics",
      "DNA Origami",
      "Genetic Variation",
      "Genomics",
      "Genome Assembly",
      "Genomic Visualization",
      "Cancer Detection",
      "Antibiotic Resistance",
      "Microbial Genomics",
    ],
  },
  {
    id: 39,
    title: "Glioblastoma",
    specificTopics: [
      "Evolutionary Biology",
      "Cancer Microenvironment",
      "Cancer Biomarkers",
      "Genetic Mutations",
      "Cancer Genomics",
      "Pharmacology",
      "Brain Cancer",
    ],
  },
  {
    id: 40,
    title: "HIV Research",
    specificTopics: ["HIV Treatment", "Viral Disease", "Viral Assembly"],
  },
  {
    id: 41,
    title: "Health Education",
    specificTopics: [
      "Academic Careers",
      "Childhood Obesity",
      "Healthcare",
      "Global Health",
      "Addiction Genetics",
    ],
  },
  {
    id: 42,
    title: "Hearing",
    specificTopics: [
      "Smell System",
      "Auditory Processing",
      "Music Theory",
      "Speech Processing",
      "Hearing Loss",
    ],
  },
  {
    id: 43,
    title: "Immune Response",
    specificTopics: [
      "Immune Repertoire",
      "HIV Vaccine",
      "Antibody Therapeutics",
      "Cancer Immunology",
    ],
  },
  {
    id: 44,
    title: "Inflammatory Bowel",
    specificTopics: ["Intestinal Cells", "Inflammatory Bowel"],
  },
  {
    id: 45,
    title: "Influenza Virus",
    specificTopics: ["Vaccine Science", "Viral Replication"],
  },
  {
    id: 46,
    title: "Insect Behavior and Ecology",
    specificTopics: [
      "Kinematics",
      "Ant Colonies",
      "Honeybee Behavior",
      "Bee Health",
    ],
  },
  {
    id: 47,
    title: "Ion Channels",
    specificTopics: ["Ion Channel", "Cell Transport", "Pain Receptors"],
  },
  {
    id: 48,
    title: "Learning Theory",
    specificTopics: [
      "Brain Function",
      "Learning Theory",
      "Motor Learning",
      "Cognitive Control",
      "Brain Chemistry",
      "Social Brain",
    ],
  },
  {
    id: 49,
    title: "Liver Inflammation",
    specificTopics: [
      "Inflammation Response",
      "Viral Infection",
      "Immune Response",
      "Immune Cells",
      "Autoimmune Disease",
      "Liver Disease",
    ],
  },
  {
    id: 50,
    title: "Malaria",
    specificTopics: [
      "Plant Extracts",
      "Parasite Biology",
      "Malaria Control",
      "Antimalarial Treatment",
      "Malaria Immunity",
    ],
  },
  {
    id: 51,
    title: "Marine Biology",
    specificTopics: [
      "Environmental DNA",
      "Salmon Genetics",
      "Climate Change",
      "Marine Mammals",
      "Water Quality",
      "Marine Fisheries",
      "Coral Reef",
      "Evolutionary Biology",
      "Aquatic Toxicity",
    ],
  },
  {
    id: 52,
    title: "Medical Imaging",
    specificTopics: [
      "Brain Mapping",
      "Neuroimaging Analysis",
      "Neuroimaging",
      "Magnetic Resonance",
      "Medical Imaging",
    ],
  },
  {
    id: 53,
    title: "Memory and Fear",
    specificTopics: [
      "Hippocampal Research",
      "Neuroscience",
      "Memory Processes",
      "PTSD Response",
    ],
  },
  {
    id: 54,
    title: "Microbial Communities",
    specificTopics: [
      "Genomics Analysis",
      "Oral Health",
      "Evolutionary Biology",
      "Metabolic Changes",
      "Vaginal Health",
    ],
  },
  {
    id: 55,
    title: "Microbial Ecology",
    specificTopics: [
      "Brewing",
      "Environmental Science",
      "Biochemical Engineering",
      "Symbiotic Relationships",
      "Ocean Ecosystems",
      "Microbiology",
      "Water Treatment",
      "Antibiotic Resistance",
    ],
  },
  {
    id: 56,
    title: "Microbial Pathogens",
    specificTopics: [
      "Fungal Genetics",
      "Parasite Biology",
      "Infection Response",
      "Clostridium difficile",
      "Infections",
      "Bacterial Infections",
      "Insect Toxins",
      "Disease Outbreak",
      "Fungal Infections",
      "Toxoplasmosis",
    ],
  },
  {
    id: 57,
    title: "Microscopy",
    specificTopics: [
      "Fluorescence Microscopy",
      "Biosensor Technology",
      "CryoEM Structures",
      "Microscopy",
      "Software Tools",
    ],
  },
  {
    id: 58,
    title: "Mitochondria",
    specificTopics: [
      "Mitochondria",
      "Evolutionary Genetics",
      "Oxidative Stress",
      "Parkinsons Disease",
    ],
  },
  {
    id: 59,
    title: "Motor Control and Movement",
    specificTopics: ["Exercise Physiology", "Motor Control"],
  },
  {
    id: 60,
    title: "Muscle Disease",
    specificTopics: ["Muscle Regeneration", "Muscular Dystrophy"],
  },
  {
    id: 61,
    title: "Nematode Biology",
    specificTopics: [
      "Neural Behavior",
      "Cell Biology",
      "Genetic Variation",
      "Genome Defense",
      "Aging",
    ],
  },
  {
    id: 62,
    title: "Neural Development",
    specificTopics: [
      "Evolutionary Biology",
      "Neuroscience",
      "Zebrafish Genetics",
      "Developmental Biology",
      "Bone Health",
      "Fibrosis",
    ],
  },
  {
    id: 63,
    title: "Neural Networks",
    specificTopics: [
      "Neural Plasticity",
      "Brain Connectivity",
      "Brain Networks",
      "Artificial Intelligence",
      "Brain Waves",
      "Brain Computer Interfaces",
      "Neural Dynamics",
      "Neuroscience",
    ],
  },
  {
    id: 64,
    title: "Neuroimaging",
    specificTopics: ["Medical Simulation"],
  },
  {
    id: 65,
    title: "Neuroscience",
    specificTopics: [
      "Neuroscience",
      "Neurotransmitter System",
      "Epilepsy",
      "Parkinsons Disease",
      "Neurology",
      "Sensory Perception",
      "Neuroanatomy",
      "Motor Control",
      "Neurotransmission",
    ],
  },
  {
    id: 66,
    title: "Noncoding RNAs",
    specificTopics: ["MicroRNAs", "Noncoding RNAs", "RNA Biology"],
  },
  {
    id: 67,
    title: "Pain Management",
    specificTopics: ["Neurological Pain", "Pain Perception", "Substance Abuse"],
  },
  {
    id: 68,
    title: "Parkinsons Disease",
    specificTopics: [
      "Genetic Disease",
      "Parkinsons Disease",
      "Eye Disease",
      "Spinal Cord Injury",
      "Neurodevelopment",
      "Neurodegeneration",
      "Epilepsy Genetics",
      "Nutrition",
      "Neuroprotective Agents",
      "Multiple Sclerosis",
      "Huntington's Disease",
      "Immune Response",
    ],
  },
  {
    id: 69,
    title: "Pharmaceuticals",
    specificTopics: [
      "Plant Extracts",
      "Enzyme Inhibitors",
      "Machine Learning",
      "Toxicology",
      "Cell Signaling",
      "Peptide Sequences",
    ],
  },
  {
    id: 70,
    title: "Photosynthesis",
    specificTopics: [
      "Ocean Microbiology",
      "Biological Optics",
      "Photosynthesis",
      "Cyanobacteria",
    ],
  },
  {
    id: 71,
    title: "Plant Stress",
    specificTopics: [
      "Plant Development",
      "Immune Response",
      "Photosynthesis",
      "RNA Regulation",
      "Cell Signaling",
      "Wheat Genetics",
      "Metabolic Pathway",
      "Plant Stress",
    ],
  },
  {
    id: 72,
    title: "Protein Analysis",
    specificTopics: ["Metabolic Flux", "Protein Analysis", "Mass Spectrometry"],
  },
  {
    id: 73,
    title: "Protein Networks",
    specificTopics: [
      "Systems Biology",
      "Protein Modeling",
      "Scientific Software",
      "Genomics",
      "Bioinformatics",
      "Protein Interactions",
    ],
  },
  {
    id: 74,
    title: "Protein Structure",
    specificTopics: [
      "Biological Assemblies",
      "Molecular Dynamics",
      "Protein Binding",
      "Evolutionary Genetics",
      "Biochemistry",
      "Protein Structure",
      "Protein Disorder",
      "Biomolecular Condensation",
    ],
  },
  {
    id: 75,
    title: "Psychological Disorders",
    specificTopics: [
      "Cannabis",
      "Reproductive Hormones",
      "Schizophrenia Genetics",
      "Food Preferences",
      "Autism Disorder",
      "Social Behavior",
      "Psychedelic Drugs",
      "Pregnancy and Birth",
      "Stress Disorders",
      "Substance Abuse",
      "Neural Plasticity",
      "Mental Health Disorder",
      "Brain Injury",
      "Alcohol Abuse",
      "Fetal Alcohol",
    ],
  },
  {
    id: 76,
    title: "Pulmonary Disease",
    specificTopics: [
      "Pulmonary Fibrosis",
      "Respiratory Health",
      "Cystic Fibrosis",
    ],
  },
  {
    id: 77,
    title: "Single Cell",
    specificTopics: [
      "Neuroscience",
      "Single Cell Omics",
      "Genomic Regulation",
      "Developmental Dynamics",
      "Single Cell Analysis",
      "Spatial Biology and Environmental Response",
    ],
  },
  {
    id: 78,
    title: "Sleep Rhythms",
    specificTopics: [
      "Sleep Research",
      "Sleep Health",
      "Circadian Rhythms",
      "Memory Consolidation",
    ],
  },
  {
    id: 79,
    title: "Soil Microbiology",
    specificTopics: [
      "Plant Disease",
      "Fungi Ecology",
      "Soil Science",
      "Plant Microbiome",
    ],
  },
  {
    id: 80,
    title: "Staphylococcal Infections",
    specificTopics: ["Bacterial Pathogens"],
  },
  {
    id: 81,
    title: "Systems Biology",
    specificTopics: [
      "Cellular Networks",
      "Statistical Modeling",
      "Epidemiology",
      "Data Clustering",
      "Metabolic Pathway",
      "Meta-Science",
    ],
  },
  {
    id: 82,
    title: "TB Disease",
    specificTopics: ["Antibiotic Resistance", "Bovine TB", "Tuberculosis"],
  },
  {
    id: 83,
    title: "Thermoregulation",
    specificTopics: [
      "Spatial Biology and Environmental Response",
      "Hibernation Physiology",
    ],
  },
  {
    id: 84,
    title: "Tissue Engineering",
    specificTopics: [
      "Microfluidics",
      "Nanoparticle Delivery",
      "Tissue Regeneration",
      "Bioprinting Materials",
      "Organoid Models",
    ],
  },
  {
    id: 85,
    title: "Virology",
    specificTopics: [
      "Evolutionary Genetics",
      "Viral Structure",
      "Microbial Diversity",
      "Herpesvirus",
      "Zika Virus",
      "Gene Therapy",
      "Viral Infections",
      "Immune Response",
    ],
  },
  {
    id: 86,
    title: "Zebrafish Biology",
    specificTopics: ["Genomic Evolution", "Animal Behavior"],
  },
  {
    id: 87,
    title: "Zoonotic Diseases",
    specificTopics: ["Avian Influenza", "Livestock Disease", "Bats and Rabies"],
  },
];

export const specificTopics = [
  "Academic Careers",
  "Addiction Genetics",
  "Adipose Tissue",
  "Aging",
  "Agriculture",
  "Alcohol Abuse",
  "Alzheimer's Diagnosis",
  "Alzheimer's Disease",
  "Anatomy",
  "Anesthesia",
  "Animal Behavior",
  "Animal Communication",
  "Animal Health",
  "Ant Colonies",
  "Antibiotic Resistance",
  "Antibody Response",
  "Antibody Therapeutics",
  "Antimalarial Treatment",
  "Aquatic Toxicity",
  "Artificial Intelligence",
  "Atherosclerosis",
  "Attention",
  "Auditory Processing",
  "Autism Disorder",
  "Autoimmune Disease",
  "Avian Influenza",
  "Bacterial Defense",
  "Bacterial Division",
  "Bacterial Genetics",
  "Bacterial Growth",
  "Bacterial Infections",
  "Bacterial Motility",
  "Bacterial Pathogens",
  "Bacterial Regulation",
  "Bacterial Secretion",
  "Bacterial Symbionts",
  "Bacteriophage Therapy",
  "Bats and Rabies",
  "Bee Health",
  "Behavioral Tracking",
  "Biochemical Engineering",
  "Biochemical Pathway",
  "Biochemistry",
  "Biodiversity Conservation",
  "Biofilm Formation",
  "Bioinformatics",
  "Biological Assemblies",
  "Biological Circuits",
  "Biological Noise",
  "Biological Optics",
  "Biomarker Analysis",
  "Biomolecular Condensation",
  "Bioprinting Materials",
  "Biosensor Technology",
  "Bird Migration",
  "Blood Cancer",
  "Blood Cells",
  "Bone Health",
  "Botany",
  "Bovine TB",
  "Brain Cancer",
  "Brain Chemistry",
  "Brain Computer Interfaces",
  "Brain Connectivity",
  "Brain Function",
  "Brain Injury",
  "Brain Mapping",
  "Brain Networks",
  "Brain Stimulation",
  "Brain Waves",
  "Breast Cancer",
  "Brewing",
  "COVID Vaccine",
  "COVID-19",
  "CRISPR Screening",
  "Calcium Signaling",
  "Cancer",
  "Cancer Biomarkers",
  "Cancer Detection",
  "Cancer Genes",
  "Cancer Genomics",
  "Cancer Immunology",
  "Cancer Metastasis",
  "Cancer Microenvironment",
  "Cancer Signaling",
  "Cancer Therapy",
  "Cannabis",
  "Cardiac Disease",
  "Cardiac Physiology",
  "Cell Adhesion",
  "Cell Biology",
  "Cell Death",
  "Cell Differentiation",
  "Cell Division",
  "Cell Growth",
  "Cell Junctions",
  "Cell Membranes",
  "Cell Migration",
  "Cell Morphology",
  "Cell Motility",
  "Cell Signaling",
  "Cell Trafficking",
  "Cell Transport",
  "Cell Wall",
  "Cellular Degradation",
  "Cellular Mechanics",
  "Cellular Networks",
  "Childhood Obesity",
  "Chromatin Dynamics",
  "Chromosome Organization",
  "Cilia Structure",
  "Circadian Rhythms",
  "Climate Change",
  "Clostridium difficile",
  "Cognitive Control",
  "Cognitive Decline",
  "Color Phenotypes",
  "Computer Vision",
  "Coral Reef",
  "Crop Genetics",
  "CryoEM Structures",
  "Cyanobacteria",
  "Cystic Fibrosis",
  "DNA Origami",
  "DNA Repair",
  "DNA Replication",
  "Data Clustering",
  "Dengue Fever",
  "Developmental Biology",
  "Developmental Dynamics",
  "Diabetes",
  "Disease Outbreak",
  "Disease Surveillance",
  "Disease Transmission",
  "Ecological Diversity",
  "Ecological Niche",
  "Ecosystem Dynamics",
  "Ecosystem Ecology",
  "Emotion Regulation",
  "Environmental DNA",
  "Environmental Science",
  "Enzyme Inhibitors",
  "Enzymology",
  "Epidemiology",
  "Epigenetics",
  "Epilepsy",
  "Epilepsy Genetics",
  "Evolutionary Biology",
  "Evolutionary Genetics",
  "Exercise Physiology",
  "Eye Cells",
  "Eye Disease",
  "Eye Movement",
  "Fetal Alcohol",
  "Fibrosis",
  "Fluorescence Microscopy",
  "Food Preferences",
  "Forestry",
  "Fruit Development",
  "Fungal Genetics",
  "Fungal Infections",
  "Fungi Ecology",
  "Gene Expression",
  "Gene Regulation",
  "Gene Therapy",
  "Genetic Analysis",
  "Genetic Disease",
  "Genetic Diversity",
  "Genetic Engineering",
  "Genetic Mutations",
  "Genetic Recombination",
  "Genetic Risk",
  "Genetic Selection",
  "Genetic Traits",
  "Genetic Variation",
  "Genetics",
  "Genome Assembly",
  "Genome Defense",
  "Genome Methylation",
  "Genomic Evolution",
  "Genomic Regulation",
  "Genomic Visualization",
  "Genomics",
  "Genomics Analysis",
  "Global Health",
  "Glycosylation",
  "HIV Treatment",
  "HIV Vaccine",
  "Healthcare",
  "Hearing Loss",
  "Heart Health",
  "Herbivore Pests",
  "Herpesvirus",
  "Hibernation Physiology",
  "Hippocampal Research",
  "Honeybee Behavior",
  "Human Genetics",
  "Huntington's Disease",
  "Hypoxia Response",
  "Immune Cells",
  "Immune Defense",
  "Immune Repertoire",
  "Immune Response",
  "Immune Signaling",
  "Immune System",
  "Infection Response",
  "Infections",
  "Inflammation Response",
  "Inflammatory Bowel",
  "Insect Toxins",
  "Intestinal Cells",
  "Ion Channel",
  "Iron Metabolism",
  "Kidney Disease",
  "Kinematics",
  "Language Processing",
  "Learning Theory",
  "Lipid Metabolism",
  "Liver Disease",
  "Livestock Disease",
  "Lung Cancer",
  "Machine Learning",
  "Magnetic Resonance",
  "Malaria Control",
  "Malaria Immunity",
  "Marine Fisheries",
  "Marine Mammals",
  "Mass Spectrometry",
  "Mechanosensitive channels",
  "Medical Imaging",
  "Medical Simulation",
  "Meiotic Process",
  "Memory Consolidation",
  "Memory Processes",
  "Mental Health Disorder",
  "Meta-Science",
  "Metabolic Changes",
  "Metabolic Flux",
  "Metabolic Pathway",
  "Metacognition",
  "MicroRNAs",
  "Microbial Communities",
  "Microbial Diversity",
  "Microbial Evolution",
  "Microbial Genomics",
  "Microbial Resistance",
  "Microbiology",
  "Microfluidics",
  "Microplastic Pollution",
  "Microscopy",
  "Mitochondria",
  "Mitotic Spindle",
  "Molecular Dynamics",
  "Molecular Testing",
  "Mosquito Control",
  "Motor Control",
  "Motor Learning",
  "Multiple Sclerosis",
  "Muscle Regeneration",
  "Muscular Dystrophy",
  "Musculoskeletal",
  "Music Theory",
  "Nanoparticle Delivery",
  "Neonatal Development",
  "Neural Behavior",
  "Neural Circuits",
  "Neural Decision",
  "Neural Dynamics",
  "Neural Plasticity",
  "Neural Responses",
  "Neuroanatomy",
  "Neurodegeneration",
  "Neurodevelopment",
  "Neuroimaging",
  "Neuroimaging Analysis",
  "Neurological Disease",
  "Neurological Pain",
  "Neurology",
  "Neuroprotective Agents",
  "Neuroscience",
  "Neurostimulation",
  "Neurotransmission",
  "Neurotransmitter System",
  "Noncoding RNAs",
  "Nutrition",
  "Obesity Research",
  "Ocean Ecosystems",
  "Ocean Microbiology",
  "Oral Health",
  "Organoid Models",
  "Ovarian Development",
  "Oxidative Stress",
  "PTSD Response",
  "Pain Perception",
  "Pain Receptors",
  "Pancreatic Cancer",
  "Pancreatic Cells",
  "Parasite Biology",
  "Parasite Genomics",
  "Parkinsons Disease",
  "Peptide Sequences",
  "Perceptual Timing",
  "Pharmacology",
  "Photosynthesis",
  "Plant Biology",
  "Plant Development",
  "Plant Disease",
  "Plant Evolution",
  "Plant Extracts",
  "Plant Genomes",
  "Plant Microbiome",
  "Plant Phenotyping",
  "Plant Stress",
  "Population Genetics",
  "Population-Level Dynamics",
  "Pregnancy",
  "Pregnancy and Birth",
  "Primates",
  "Protein Analysis",
  "Protein Binding",
  "Protein Degradation",
  "Protein Disorder",
  "Protein Interactions",
  "Protein Modeling",
  "Protein Modification",
  "Protein Structure",
  "Protein Synthesis",
  "Protein Translation",
  "Psychedelic Drugs",
  "Psychiatric Disorders",
  "Pulmonary Fibrosis",
  "Pulmonary Hypertension",
  "RNA Binding",
  "RNA Biology",
  "RNA Editing",
  "RNA Modification",
  "RNA Regulation",
  "RNA Structure",
  "Reproductive Biology",
  "Reproductive Hormones",
  "Respiratory Health",
  "Salmon Genetics",
  "Schizophrenia Genetics",
  "Scientific Software",
  "Sensory Chemistry",
  "Sensory Perception",
  "Sex Determination",
  "Single Cell Analysis",
  "Single Cell Omics",
  "Sleep Health",
  "Sleep Research",
  "Smell System",
  "Social Behavior",
  "Social Brain",
  "Social Networks",
  "Software Tools",
  "Soil Science",
  "Soybean Genetics",
  "Spatial Biology and Environmental Response",
  "Spatial Navigation",
  "Species Identification",
  "Speech Processing",
  "Spinal Cord Injury",
  "Statistical Modeling",
  "Statistical Modelling",
  "Stem Cell",
  "Stem Cell Biology",
  "Stress Disorders",
  "Stress Response",
  "Substance Abuse",
  "Symbiotic Relationships",
  "Systems Biology",
  "Tauopathies",
  "Technology Development",
  "Telomere Maintenance",
  "Thermal Tolerance",
  "Tissue Regeneration",
  "Toxicology",
  "Toxoplasmosis",
  "Transcription Factors",
  "Transposons",
  "Tuberculosis",
  "Vaccine Development",
  "Vaccine Science",
  "Vaginal Health",
  "Vascular Biology",
  "Vascular System",
  "Viral Assembly",
  "Viral Disease",
  "Viral Diseases",
  "Viral Entry",
  "Viral Infection",
  "Viral Infections",
  "Viral Replication",
  "Viral Structure",
  "Virus Variants",
  "Vision",
  "Water Quality",
  "Water Treatment",
  "Wheat Genetics",
  "Wildfire Ecology",
  "Wildlife Tracking",
  "Women's Health",
  "Zebrafish Genetics",
  "Zika Virus",
  "mRNA degradation",
];
